# Generated by Django 5.2.7 on 2025-10-06 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('descripcion_corta', models.CharField(max_length=250)),
                ('descripcion_detallada', models.TextField()),
                ('fecha_hora', models.DateTimeField()),
                ('url_streaming', models.URLField(blank=True, help_text='Enlace al webinar/meet.', null=True)),
                ('ponente', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('conferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='eventos.conferencia')),
            ],
            options={
                'unique_together': {('conferencia', 'email')},
            },
        ),
    ]
