# Generated by Django 5.2.7 on 2025-10-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasoEstudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('nicho_cliente', models.CharField(help_text='Ej: FinTech, LegalTech', max_length=100)),
                ('problema', models.TextField()),
                ('solucion_ia', models.TextField(verbose_name='Solución Implementada (LLM/IA)')),
                ('resultado_clave', models.TextField(help_text='Métrica cuantificable: Ej: 30% reducción de latencia.')),
                ('enlace_github', models.URLField(blank=True, null=True, verbose_name='GitHub del POC')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
